### ISSUE TITLE
fails with gradle 4.10.2

### ISSUE THREAD

**Issue by jordandev** [wfhartford/gradle-helm#8]
Get this when using this plugin with gradle 4.10.2:

```
12:58:34 Caused by: java.lang.NoSuchMethodError: org.gradle.kotlin.dsl.NamedDomainObjectContainerScope.invoke(Ljava/lang/String;)Ljava/lang/Object;
12:58:34 	at ca.cutterslade.gradle.helm.HelmPlugin.apply(HelmPlugin.kt:472)
12:58:34 	at ca.cutterslade.gradle.helm.HelmPlugin.apply(HelmPlugin.kt:38)
12:58:34 	at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:42)
12:58:34 	at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:50)
12:58:34 	at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:174)
12:58:34 	at org.gradle.api.internal.plugins.DefaultPluginManager.access$300(DefaultPluginManager.java:50)
12:58:34 	at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:264)
12:58:34 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
12:58:34 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
12:58:34 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
12:58:34 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
12:58:34 	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
12:58:34 	at org.gradle.api.internal.plugins.DefaultPluginManager$2.execute(DefaultPluginManager.java:152)
12:58:34 	at org.gradle.api.internal.plugins.DefaultPluginManager$2.execute(DefaultPluginManager.java:149)
12:58:34 	at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:48)
12:58:34 	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:149)
12:58:34 	at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:130)
12:58:34 	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:120)
12:58:34 	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:38)
12:58:34 	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:86)
12:58:34 	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:143)
12:58:34 	at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:46)
12:58:34 	at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.java:34)
12:58:34 	at org.gradle.api.Script$apply.callCurrent(Unknown Source)
12:58:34 	at build_blfrc6ilb6m2uxklmeayuiry6.run(/home/jenkins/workspace/kube-nightly-deploy-zema/helm/build.gradle:9)
12:58:34 	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:90)
12:58:34 	... 91 more`
```

**Comment by jordandev** [comment]
Works ok with 4.9

**Comment by jordandev** [comment]
Works now with gradle 4.10.2 and 1.0.0-beta-8
